name: Sand System Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install CUDA
        uses: Jimver/cuda-toolkit@v0.2.19
        with:
          cuda: '11.8.0'

      - name: Build dockerfile
        run: |
          docker build -f docker/Dockerfile .
